run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/aforoai/aforo-nextgen-loadgen
  gocritic:
    disabled-checks:
      - ifElseChain
  revive:
    rules:
      - name: var-naming
      - name: exported
      - name: error-return
      - name: error-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
